apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  # Las contraseñas deben estar en base64
  # '1234' en base64 es 'MTIzNA=='
  mysql-root-password: MTIzNA==
  mysql-password: MTIzNA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  mysql-database: "proyecto_go"
  mysql-user: "usuariodb"

#Nota: Para obtener el valor base64 de tu contraseña en Linux/WSL puedes usar: echo -n "1234" | base64.