apiVersion: v1
kind: Pod
metadata:
  name: mysql-test-app
spec:
  containers:
  - name: mysql-client
    image: mariadb:10.11
    command: ["sh", "-c", "sleep 5 && mysql -h db -u $DB_USER -p$DB_PASS $DB_NAME -e 'SELECT * FROM usuarios;' && sleep 3600"]
    env:
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: mysql-user
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: mysql-password
    - name: DB_HOST
      value: "db"
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: mysql-database
  restartPolicy: Never
